# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c75a520eeb60d3f50b2d42ce87ad4b068264de541d38b2467d75915ab7d73273d0eb7bd72f18b0b97db8e75f438a6837d132eeb6cfb0925c3a03096c2c8080c

test:
  secret_key_base: 596b120b801880e91415c3c4cad54f27efb354190f41201d2f8a522d0191e85b893ce132d6775c8b51a1c3b032ab822b62d7086e1bbace6828c339aa8f8354db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
